
name: Test pipeline

on:
  push:

jobs:
  demo1:
    runs-on: Linux

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Printing some statement
        run: echo "Running successfully"
