name: Demo Pipeline

on:
  push:
    branches:
      - nodeapp

jobs:
  demo:
    runs-on: githubactions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print the details
        run: echo "code checkout"
